### PR TITLE
Added the ability to choose which exceptions to retry using a predicate

### PR DESCRIPTION
**Pull request by coreagile**
A bit of cleanup in the test cases to remove duplication and some unused
bindings.

Note: I admit I went a bit overboard in my refactoring. If you'd like I can pare it down to just the essential change to introduce the feature.

Looking forward to seeing what you think!

### CODE REVIEW

**Comment by liwp** [comment]
The feature looks good to me after a quick peak.

I'm not sure about the test refactoring simply because it introduces a level of macro magic for relatively little benefit: it the win in removed duplication worth the extra cognitive load on the reader when they have to i) understand what `defsleeplesstest` does differently from `deftest`, and ii) should they use `defsleeplesstest` or `deftest` in their own test.

I'll have a closer look during the weekend and try to get it merged then.

Thanks again for your help!

**Comment by coreagile** [comment]
Ok! If you need me to undo the macro magic I’m happy to!

**Comment by coreagile** [comment]
Also, what's the likelihood of a release post-merge? I'd like to stop depending on our custom built version as soon as possible.

**Comment by liwp** [comment]
Yes, I'd like to make a release after the merge. I'm hoping to release `1.0.0` based on this PR and the `next-release` branch.

I'm also looking to change the package org from `listora` to `liwp` since Listora doesn't exist anymore, but I think I'll do this as a separate release. Obviously users would have to change their `require`s from `listora.again` to `liwp.again`, and package update checker tooling wouldn't catch the new release, but otherwise I think the package name change would be benign.

**Comment by coreagile** [comment]
Great!

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Pull request merged**
